version: '3.4'
services:
  dramabot:
    container_name: dramabot
    image: dramabot:latest
    environment:
      - TZ=Europe/Berlin
    build: 
      context: ./
    ports:
# format: "port-on-docker-host:port-in-docker-container"
# webhook port
      - "8081:8081"
    volumes:
# mount local directories in docker-container
      - ./config:/config
      - ./log:/log
volumes:
  config:
    driver: local
  log:
    driver: local

